<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAleM2FF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAleM2FF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAleM2FF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAleM2FF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAleM2FF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AleM2FF',
    'container.build_id' => '2f944eb0',
    'container.build_time' => 1612124715,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAleM2FF');
